Changes to collect shard indexing pressure metrics and push to shared location
opendistro-for-elasticsearch/performance-analyzer pull request #278
Opened 2021-02-23 14:37 UTC by psychbot

*Issue #, if available:* NA

*Description of changes:*
Code changes to add a new collector to collect the information specific to shard indexing pressure(AES feature).
Below are the metrics that will be collected.
1. isActiveShard - Keeps track of when the shard was active(logic is internal to AES) and when it wasn't
2. rejectionCount - Keeps track of the rejection count.
3. currentBytes - Keeps track of the inflight request size.
4. currentLimits - Keeps track of the shard limits(logic internal to AES).
5. averageWindowThroughput - Keeps track of the average throughput of last N requests.
6. lastSuccessfulTimestamp - Keeps track of the timestamp of last successful request.

These metrics are published with following dimensions -
1. nodeRole - Coordinating, Primary or replica.
2. indexName - Name of the index.
3. shardId - Id of the shard.

Made sure that the code path is executed only when some of the AES specific classes are present.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

2021-02-25 17:48 UTC, yojs commented on src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/PerformanceAnalyzerPlugin.java
> +        scheduledMetricCollectorsExecutor.addScheduledMetricCollector(new ShardIndexingPressureMetricsCollector(
Let's add the check for `Class.forName(SHARD_INDEXING_PRESSURE_CLASS_NAME);` here. That way the collector never runs if the dependency is not available.

2021-02-25 17:48 UTC, yojs commented on src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/collectors/ShardIndexingPressureMetricsCollector.java
> +            LOG.debug("Shard IndexingPressure not present in this ES version. Skipping ShardIndexingPressureMetricsCollector");
I am worried that for cases, when the plugin is not installed, we might fill up the logs. We should just emit the log once at first run.

2021-02-25 21:03 UTC, yojs approved these changes

2021-02-25 21:08 UTC, yojs requested changes

2021-02-25 21:08 UTC, yojs commented on src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/PerformanceAnalyzerPlugin.java
> +            return;
We should not return here

2021-02-25 22:10 UTC, yojs commented on src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/collectors/ShardIndexingPressureMetricsCollector.java
> +                            LOG.debug("Exception raised while parsing string to json object. Skipping IndexingPressureMetricsCollector");
The default log level is not debug. So, how would we know if this exception is generated often ?

2021-02-25 22:10 UTC, yojs commented on src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/collectors/ShardIndexingPressureMetricsCollector.java
> +}
nit: A new line to end the file ?

2021-02-25 22:11 UTC, yojs approved these changes

2021-02-26 17:16 UTC, yojs approved these changes

2021-02-26 18:26 UTC, ktkrg approved these changes

2021-02-26 18:37 UTC, khushbr commented on src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/collectors/ShardIndexingPressureMetricsCollector.java
> +                    Map<Long, Object> shardIndexingPressureHotStore =
Did we do stress testing here for shardIndexingPressure metric collection ? What is max size of `shardIndexingPressureHotStore` allowed and how much time did the metric collection take for this max size?

2021-03-02 06:03 UTC, merged